package com.anadolusigorta.campaignmanagement.infrastructure.customerpolicyreward.jpa.repository;

import com.anadolusigorta.campaignmanagement.infrastructure.customerpolicyreward.jpa.entity.PolicySaleGiftCodeInformationDetailEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface PolicySaleGiftCodeInformationDetailJpaRepository extends JpaRepository<PolicySaleGiftCodeInformationDetailEntity, Long> {
}
